version: "3.7"
services:
  app:
    image: luz-do-saber_banco:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /srv/database/data:/var/lib/postgresql/data
    environment: 
    - TZ=America/Fortaleza
    - POSTGRES_NAME=db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=kuth2Baechai1Aetai3mubuquie5ael9
    networks:
    - traefik-public
    ports:
    - "5432:5432"
        
networks:
  traefik-public:
    external: true
