version: "3.7"

services:
  editor:
    image: luzdosaber-application:v1
    environment:
      - TZ=America/Fortaleza
      - env_file=.env  
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.editor-http.rule=Host(`{editor.thiagoqueiroz.gq}`)
        - traefik.http.routers.editor-http.entrypoints=http
        - traefik.http.routers.editor-http.middlewares=https-redirect
        - traefik.http.routers.editor-https.rule=Host(`{editor.thiagoqueiroz.gq}`)
        - traefik.http.routers.editor-https.entrypoints=https
        - traefik.http.routers.editor-https.tls=true
        - traefik.http.routers.editor-https.tls.certresolver=le
        - traefik.http.services.editor.loadbalancer.server.port=80
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true